version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
    environment:
      - SSH_PASS=1234
      - DB_HOST=db
      - DB_USER=sample
      - DB_PASS=password
      - DB_NAME=sample
    volumes:
      - "./server:/home/builduser"
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - 4000:4000
    volumes:
      - "./client:/home/builduser"
  db:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=password
    volumes:
      - "data:/var/lib/postgresql/data"
volumes:
  data:
